import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section>
          <Image src="/nova.svg" alt="nebula" />
          <Image src="/thanos.svg" alt="nebula" />
          <Image src="/nebula.svg" alt="nebula" />
        </section>
      </main>
    </div>
  )
}
